# Generated by Django 6.0.6 on 2026-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
