# Generated by Django 6.0.6 on 2026-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0006_alter_courses_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='id',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
