# Generated by Django 6.0.6 on 2026-07-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0008_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=100)),
                ('class10', models.FloatField()),
                ('class12', models.FloatField()),
                ('course', models.CharField(max_length=100)),
                ('aadhaar', models.CharField(max_length=100)),
                ('aadhaar_photo', models.ImageField(upload_to='aadhaarphoto')),
                ('student_photo', models.ImageField(upload_to='studentphoto')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
