# Generated by Django 6.0.6 on 2026-07-27 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0010_delete_application_student_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Document Verified', 'Document Verified'), ('Fees Submitted', 'Fees Submitted'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='course_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='paymentscreenshots/'),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhaar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to='applications/'),
        ),
    ]
