# Generated by Django 6.0.6 on 2026-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0011_student_application_status_student_course_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending'), ('submitted', 'submitted'), ('rejected', 'rejected')], default='pending', max_length=20),
        ),
    ]
