# Generated by Django 6.0.6 on 2026-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0012_alter_student_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='student',
            name='application_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Document Verified', 'Document Verified'), ('Fees Submitted', 'Fees Submitted'), ('Enrolled', 'Enrolled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
