# Generated by Django 6.0.6 on 2026-08-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionapp', '0014_alter_student_address_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='courseimg',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
