# Generated by Django 5.1.3 on 2026-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissionapp", "0015_courses_courseimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
